version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run :
          name: Install flask
          command: 
            pip install flask
      - run : 
          name: compile python app
          command: 
            python -m py_compile app.py
  deploy:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - run :
          name: Install python dependencies
          command: |
            #! /bin/bash
            sudo apt update -y
            sudo apt install python3 -y
            sudo apt install python3-flask -y
            flask --version
      - run :
          name: Connect to ec2 instance
          command: |
            #! /bin/bash
            echo Start deploy
            ssh -o StrictHostKeyChecking=no $user@$IP https://github.com/subin-krishna-test/flaskapptest.git app sudo nohup python3 app/app.py > log.txt 2>&1 &
              
            
workflows:
  build-work:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build

  # scp -o StrictHostKeyChecking=no app.py ubuntu@13.58.112.245

